# Generated by Django 5.0 on 2023-12-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover_link', models.URLField(max_length=500)),
                ('language', models.CharField(max_length=25)),
                ('subtitle', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('drive_link', models.URLField(max_length=500)),
                ('screenshot_1', models.URLField(max_length=500)),
                ('screenshot_2', models.URLField(max_length=500)),
                ('screenshot_3', models.URLField(max_length=500)),
                ('screenshot_4', models.URLField(max_length=500)),
            ],
        ),
    ]
