# Generated by Django 5.0 on 2023-12-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_details',
            old_name='drive_link',
            new_name='d_link',
        ),
        migrations.RenameField(
            model_name='movie_details',
            old_name='screenshot_1',
            new_name='ss_1',
        ),
        migrations.RenameField(
            model_name='movie_details',
            old_name='screenshot_2',
            new_name='ss_2',
        ),
        migrations.RenameField(
            model_name='movie_details',
            old_name='screenshot_3',
            new_name='ss_3',
        ),
        migrations.RenameField(
            model_name='movie_details',
            old_name='screenshot_4',
            new_name='ss_4',
        ),
        migrations.RenameField(
            model_name='movie_details',
            old_name='description',
            new_name='textbox',
        ),
    ]
